Watching for file changes with StatReloader
Not Found: /favicon.ico/
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\template\base.py", line 875, in _resolve_lookup
    current = current[bit]
TypeError: 'Book' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\test\utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\test\utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\template\defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\template\loader_tags.py", line 208, in render
    return template.render(context)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\template\base.py", line 177, in render
    return self._render(context)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\test\utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\template\base.py", line 1059, in render
    output = self.filter_expression.resolve(context)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\template\base.py", line 712, in resolve
    obj = self.var.resolve(context)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\template\base.py", line 842, in resolve
    value = self._resolve_lookup(context)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = getattr(current, bit)
  File "C:\Users\HP\Desktop\projects\books\books\models.py", line 28, in cover
    pdf= fitz.open(url)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\fitz\fitz.py", line 3990, in __init__
    raise FileNotFoundError(msg)
fitz.fitz.FileNotFoundError: no such file: '/media/book/pdfs/Data_Structures_and_Algorithms_in_Java_5Pvzvsd.pdf'
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /static/debug_toolbar/css/toolbar.css
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/debug_toolbar/js/toolbar.js
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/debug_toolbar/css/print.css
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Not Found: /favicon.ico/
Internal Server Error: /static/debug_toolbar/css/print.css
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/debug_toolbar/css/toolbar.css
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
C:\Users\HP\Desktop\projects\books\config\settings\common.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\config\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\config\settings\common.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\config\settings\common.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /create/
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\generic\base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\generic\edit.py", line 184, in post
    return super().post(request, *args, **kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_valid(form)
  File "C:\Users\HP\Desktop\projects\books\books\views.py", line 27, in form_valid
    return super().form_valid(form)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\generic\edit.py", line 135, in form_valid
    self.object = form.save()
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\forms\models.py", line 548, in save
    self.instance.save()
  File "C:\Users\HP\Desktop\projects\books\books\models.py", line 48, in save
    self.cover_url= cover(self)
  File "C:\Users\HP\Desktop\projects\books\books\models.py", line 14, in cover
    pdf= fitz.open(url)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\fitz\fitz.py", line 3990, in __init__
    raise FileNotFoundError(msg)
fitz.fitz.FileNotFoundError: no such file: '/media/The%20Lean%20Startup.pdf'
Not Found: //anything-but-admin/books/book/
Internal Server Error: /static/admin/css/nav_sidebar.css
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/admin/css/responsive.css
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/admin/css/base.css
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/admin/css/login.css
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/admin/js/nav_sidebar.js
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/admin/css/login.css
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/admin/css/nav_sidebar.css
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/admin/css/responsive.css
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/admin/css/base.css
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/admin/css/nav_sidebar.css
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/admin/css/base.css
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/admin/css/responsive.css
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/admin/css/login.css
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/admin/js/nav_sidebar.js
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/admin/css/base.css
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/admin/css/nav_sidebar.css
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/admin/css/responsive.css
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/admin/css/dashboard.css
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/admin/js/nav_sidebar.js
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/admin/css/base.css
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/admin/js/jquery.init.js
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/admin/css/responsive.css
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/admin/css/changelists.css
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/admin/css/nav_sidebar.css
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/admin/js/core.js
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/admin/js/urlify.js
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/admin/js/admin/RelatedObjectLookups.js
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/admin/js/actions.js
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/admin/js/prepopulate.js
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/admin/js/vendor/xregexp/xregexp.js
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/admin/js/vendor/jquery/jquery.js
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/admin/js/nav_sidebar.js
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/admin/css/responsive.css
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/admin/css/base.css
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/admin/css/changelists.css
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/admin/js/core.js
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/admin/js/admin/RelatedObjectLookups.js
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/admin/css/nav_sidebar.css
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/admin/js/vendor/jquery/jquery.js
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/admin/css/responsive.css
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/admin/js/jquery.init.js
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/admin/js/actions.js
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/admin/js/urlify.js
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/admin/js/prepopulate.js
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/admin/js/vendor/xregexp/xregexp.js
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/admin/js/nav_sidebar.js
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/admin/css/responsive.css
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Internal Server Error: /static/admin/img/search.svg
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
C:\Users\HP\Desktop\projects\books\config\settings\common.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\config\settings\common.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\config\urls.py changed, reloading.
Watching for file changes with StatReloader
Forbidden (CSRF token from POST incorrect.): /create/
Internal Server Error: /create/
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\generic\base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\generic\edit.py", line 184, in post
    return super().post(request, *args, **kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_valid(form)
  File "C:\Users\HP\Desktop\projects\books\books\views.py", line 27, in form_valid
    return super().form_valid(form)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\generic\edit.py", line 135, in form_valid
    self.object = form.save()
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\forms\models.py", line 548, in save
    self.instance.save()
  File "C:\Users\HP\Desktop\projects\books\books\models.py", line 48, in save
    self.cover_url= cover(self)
  File "C:\Users\HP\Desktop\projects\books\books\models.py", line 14, in cover
    pdf= fitz.open(url)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\fitz\fitz.py", line 3990, in __init__
    raise FileNotFoundError(msg)
fitz.fitz.FileNotFoundError: no such file: '/media/The%20Lean%20Startup.pdf'
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /create/
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\generic\base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\generic\edit.py", line 184, in post
    return super().post(request, *args, **kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_valid(form)
  File "C:\Users\HP\Desktop\projects\books\books\views.py", line 27, in form_valid
    return super().form_valid(form)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\generic\edit.py", line 135, in form_valid
    self.object = form.save()
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\forms\models.py", line 548, in save
    self.instance.save()
  File "C:\Users\HP\Desktop\projects\books\books\models.py", line 46, in save
    self.cover_url= cover(self.pdf.url,self.title)
  File "C:\Users\HP\Desktop\projects\books\books\models.py", line 13, in cover
    pdf= fitz.open(url)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\fitz\fitz.py", line 3990, in __init__
    raise FileNotFoundError(msg)
fitz.fitz.FileNotFoundError: no such file: '/media/The%20Lean%20Startup.pdf'
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /create/
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\generic\base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\generic\edit.py", line 184, in post
    return super().post(request, *args, **kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_valid(form)
  File "C:\Users\HP\Desktop\projects\books\books\views.py", line 27, in form_valid
    return super().form_valid(form)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\generic\edit.py", line 135, in form_valid
    self.object = form.save()
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\forms\models.py", line 548, in save
    self.instance.save()
  File "C:\Users\HP\Desktop\projects\books\books\models.py", line 47, in save
    self.cover_url= cover(self.pdf.url,self.title)
  File "C:\Users\HP\Desktop\projects\books\books\models.py", line 13, in cover
    pdf= fitz.open(url)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\fitz\fitz.py", line 3990, in __init__
    raise FileNotFoundError(msg)
fitz.fitz.FileNotFoundError: no such file: '/media/book/pdfs/The_Lean_Startup.pdf'
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /profile/None
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /3715a137-c2e3-4359-a310-78b3ece6c58f/delete/
Not Found: /profile/None
Not Found: /profile/None
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /profile/None
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /create/
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\projects\books\books\models.py", line 49, in save
    self.cover_url= cover(self.pdf.url,self.title)
  File "C:\Users\HP\Desktop\projects\books\books\models.py", line 13, in cover
    pdf= fitz.open(url)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\fitz\fitz.py", line 3990, in __init__
    raise FileNotFoundError(msg)
fitz.fitz.FileNotFoundError: no such file: '/media/book/pdfs/Amir_Baap_G_B.pdf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\generic\base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\generic\edit.py", line 184, in post
    return super().post(request, *args, **kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_valid(form)
  File "C:\Users\HP\Desktop\projects\books\books\views.py", line 27, in form_valid
    return super().form_valid(form)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\generic\edit.py", line 135, in form_valid
    self.object = form.save()
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\forms\models.py", line 548, in save
    self.instance.save()
  File "C:\Users\HP\Desktop\projects\books\books\models.py", line 51, in save
    print("this the error in book model "+e)
TypeError: can only concatenate str (not "FileNotFoundError") to str
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /profile/None
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /profile/media/book/covers/Algo.png
Not Found: /profile/media/book/covers/Algo.png
Not Found: /profile/media/book/covers/Algo.png
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\books\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\Desktop\projects\books\config\settings\common.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /favicon.ico/
Internal Server Error: /static/admin/css/login.css
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\views\static.py", line 35, in serve
    fullpath = Path(safe_join(document_root, path))
  File "C:\Users\HP\.virtualenvs\books--bXnkLlY\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
C:\Users\HP\Desktop\projects\books\config\settings\common.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/code/config/settings/dev.py changed, reloading.
Watching for file changes with StatReloader
/code/config/settings/dev.py changed, reloading.
Watching for file changes with StatReloader
/code/config/settings/dev.py changed, reloading.
Watching for file changes with StatReloader
/code/config/settings/dev.py changed, reloading.
Watching for file changes with StatReloader
/code/config/settings/dev.py changed, reloading.
Watching for file changes with StatReloader
/code/config/settings/dev.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /admin/
Not Found: /favicon.ico/
Not Found: /admin/
Watching for file changes with StatReloader
Not Found: /favicon.ico/
Watching for file changes with StatReloader
Not Found: /favicon.ico/
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /profile/
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/template/smartif.py", line 179, in translate_token
    op = OPERATORS[token]
KeyError: '<a'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/usr/local/lib/python3.10/site-packages/django/template/backends/django.py", line 62, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/usr/local/lib/python3.10/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.10/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 197, in render
    template = context.template.engine.select_template(template_name)
  File "/usr/local/lib/python3.10/site-packages/django/template/engine.py", line 207, in select_template
    return self.get_template(template_name)
  File "/usr/local/lib/python3.10/site-packages/django/template/engine.py", line 176, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/local/lib/python3.10/site-packages/django/template/engine.py", line 158, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 954, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 854, in do_for
    nodelist_loop = parser.parse(
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 961, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 886, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/template/smartif.py", line 170, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "/usr/local/lib/python3.10/site-packages/django/template/smartif.py", line 181, in translate_token
    return self.create_var(token)
  File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 889, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 701, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '<a' from '<a'
Internal Server Error: /profile/
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/template/smartif.py", line 179, in translate_token
    op = OPERATORS[token]
KeyError: '<a'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/usr/local/lib/python3.10/site-packages/django/template/backends/django.py", line 62, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/usr/local/lib/python3.10/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.10/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 197, in render
    template = context.template.engine.select_template(template_name)
  File "/usr/local/lib/python3.10/site-packages/django/template/engine.py", line 207, in select_template
    return self.get_template(template_name)
  File "/usr/local/lib/python3.10/site-packages/django/template/engine.py", line 176, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/local/lib/python3.10/site-packages/django/template/engine.py", line 158, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 954, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 854, in do_for
    nodelist_loop = parser.parse(
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 961, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 886, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/template/smartif.py", line 170, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "/usr/local/lib/python3.10/site-packages/django/template/smartif.py", line 181, in translate_token
    return self.create_var(token)
  File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 889, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 701, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '<a' from '<a'
Internal Server Error: /profile/
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/usr/local/lib/python3.10/site-packages/django/template/backends/django.py", line 62, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/usr/local/lib/python3.10/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.10/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 197, in render
    template = context.template.engine.select_template(template_name)
  File "/usr/local/lib/python3.10/site-packages/django/template/engine.py", line 207, in select_template
    return self.get_template(template_name)
  File "/usr/local/lib/python3.10/site-packages/django/template/engine.py", line 176, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/local/lib/python3.10/site-packages/django/template/engine.py", line 158, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 954, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 854, in do_for
    nodelist_loop = parser.parse(
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 961, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/usr/local/lib/python3.10/site-packages/django/template/smartif.py", line 197, in parse
    raise self.error_class(
django.template.exceptions.TemplateSyntaxError: Unused 'page_obj.number|add:'3'' at end of if expression.
Internal Server Error: /profile/
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/usr/local/lib/python3.10/site-packages/django/template/backends/django.py", line 62, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/usr/local/lib/python3.10/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.10/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 197, in render
    template = context.template.engine.select_template(template_name)
  File "/usr/local/lib/python3.10/site-packages/django/template/engine.py", line 207, in select_template
    return self.get_template(template_name)
  File "/usr/local/lib/python3.10/site-packages/django/template/engine.py", line 176, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/local/lib/python3.10/site-packages/django/template/engine.py", line 158, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 954, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 854, in do_for
    nodelist_loop = parser.parse(
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 961, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/usr/local/lib/python3.10/site-packages/django/template/smartif.py", line 197, in parse
    raise self.error_class(
django.template.exceptions.TemplateSyntaxError: Unused 'page_obj.number|add:'3'' at end of if expression.
Internal Server Error: /profile/
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/usr/local/lib/python3.10/site-packages/django/template/backends/django.py", line 62, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/usr/local/lib/python3.10/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.10/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 197, in render
    template = context.template.engine.select_template(template_name)
  File "/usr/local/lib/python3.10/site-packages/django/template/engine.py", line 207, in select_template
    return self.get_template(template_name)
  File "/usr/local/lib/python3.10/site-packages/django/template/engine.py", line 176, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/local/lib/python3.10/site-packages/django/template/engine.py", line 158, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 954, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 854, in do_for
    nodelist_loop = parser.parse(
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 961, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/usr/local/lib/python3.10/site-packages/django/template/smartif.py", line 197, in parse
    raise self.error_class(
django.template.exceptions.TemplateSyntaxError: Unused 'page_obj.number|add:'3'' at end of if expression.
Internal Server Error: /profile/
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/usr/local/lib/python3.10/site-packages/django/template/backends/django.py", line 62, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/usr/local/lib/python3.10/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.10/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 197, in render
    template = context.template.engine.select_template(template_name)
  File "/usr/local/lib/python3.10/site-packages/django/template/engine.py", line 207, in select_template
    return self.get_template(template_name)
  File "/usr/local/lib/python3.10/site-packages/django/template/engine.py", line 176, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/local/lib/python3.10/site-packages/django/template/engine.py", line 158, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 954, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 854, in do_for
    nodelist_loop = parser.parse(
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 961, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/usr/local/lib/python3.10/site-packages/django/template/smartif.py", line 197, in parse
    raise self.error_class(
django.template.exceptions.TemplateSyntaxError: Unused 'page_obj.number|add:'3'' at end of if expression.
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /favicon.ico/
/code/config/settings/dev.py changed, reloading.
Watching for file changes with StatReloader
/code/config/settings/common.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/code/books/models.py changed, reloading.
Watching for file changes with StatReloader
/code/books/models.py changed, reloading.
Watching for file changes with StatReloader
/code/books/models.py changed, reloading.
Watching for file changes with StatReloader
/code/books/models.py changed, reloading.
Watching for file changes with StatReloader
/code/books/models.py changed, reloading.
Watching for file changes with StatReloader
/code/books/models.py changed, reloading.
Watching for file changes with StatReloader
/code/books/models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /favicon.ico/
Internal Server Error: /profile/
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/usr/local/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/usr/local/lib/python3.10/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/usr/local/lib/python3.10/site-packages/django/template/engine.py", line 176, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/local/lib/python3.10/site-packages/django/template/engine.py", line 158, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 968, in do_if
    nodelist = parser.parse(("endif",))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 34: 'endblock', expected 'endif'. Did you forget to register or load this tag?
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /images/favicon.png
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/usr/local/lib/python3.10/site-packages/django/template/backends/django.py", line 62, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/usr/local/lib/python3.10/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "/usr/local/lib/python3.10/site-packages/django/template/engine.py", line 158, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.10/site-packages/django/templatetags/static.py", line 171, in do_static
    return StaticNode.handle_token(parser, token)
  File "/usr/local/lib/python3.10/site-packages/django/templatetags/static.py", line 145, in handle_token
    path = parser.compile_filter(bits[1])
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 701, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ''/images/favicon.png'' from 'url'/images/favicon.png''
Watching for file changes with StatReloader
Not Found: /favicon.ico/
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/accounts/views.py changed, reloading.
Watching for file changes with StatReloader
/code/accounts/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /accounts/2/edit/
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 135, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/edit.py", line 204, in get
    return super().get(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/edit.py", line 144, in get
    return self.render_to_response(self.get_context_data())
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/edit.py", line 74, in get_context_data
    kwargs["form"] = self.get_form()
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/edit.py", line 38, in get_form
    form_class = self.get_form_class()
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/edit.py", line 110, in get_form_class
    return model_forms.modelform_factory(model, fields=self.fields)
  File "/usr/local/lib/python3.10/site-packages/django/forms/models.py", line 648, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
  File "/usr/local/lib/python3.10/site-packages/django/forms/models.py", line 327, in __new__
    raise FieldError(message)
django.core.exceptions.FieldError: Unknown field(s) (password1, password2) specified for CustomUser
/code/accounts/views.py changed, reloading.
Watching for file changes with StatReloader
/code/accounts/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /accounts/2/edit/
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 132, in dispatch
    user_test_result = self.get_test_func()()
  File "/code/accounts/views.py", line 19, in test_func
    user= self.get_object()
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/detail.py", line 31, in get_object
    queryset = self.get_queryset()
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/detail.py", line 72, in get_queryset
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: ProfileUpdateView is missing a QuerySet. Define ProfileUpdateView.model, ProfileUpdateView.queryset, or override ProfileUpdateView.get_queryset().
/code/accounts/views.py changed, reloading.
Watching for file changes with StatReloader
/code/accounts/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /accounts/2/edit/
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 132, in dispatch
    user_test_result = self.get_test_func()()
  File "/code/accounts/views.py", line 19, in test_func
    user= self.get_object()
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/detail.py", line 31, in get_object
    queryset = self.get_queryset()
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/detail.py", line 72, in get_queryset
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: ProfileUpdateView is missing a QuerySet. Define ProfileUpdateView.model, ProfileUpdateView.queryset, or override ProfileUpdateView.get_queryset().
/code/accounts/forms.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /accounts/2/edit/
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 132, in dispatch
    user_test_result = self.get_test_func()()
  File "/code/accounts/views.py", line 19, in test_func
    user= self.get_object()
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/detail.py", line 31, in get_object
    queryset = self.get_queryset()
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/detail.py", line 72, in get_queryset
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: ProfileUpdateView is missing a QuerySet. Define ProfileUpdateView.model, ProfileUpdateView.queryset, or override ProfileUpdateView.get_queryset().
/code/accounts/forms.py changed, reloading.
Watching for file changes with StatReloader
/code/accounts/forms.py changed, reloading.
Watching for file changes with StatReloader
/code/accounts/forms.py changed, reloading.
Watching for file changes with StatReloader
/code/accounts/forms.py changed, reloading.
Watching for file changes with StatReloader
/code/accounts/forms.py changed, reloading.
Watching for file changes with StatReloader
/code/accounts/admin.py changed, reloading.
Watching for file changes with StatReloader
/code/accounts/admin.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /favorite/
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 657, in get_or_create
    return self.get(**kwargs), False
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 496, in get
    raise self.model.DoesNotExist(
books.models.Favorite.DoesNotExist: Favorite matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "books_favorite_pkey"
DETAIL:  Key (id)=(144f51e8-a6de-4b5f-88c3-5706dd0bb3ff) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/code/books/views.py", line 79, in get_fav_book_list
    fav, created = Favorite.objects.get_or_create(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 664, in get_or_create
    return self.create(**params), True
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 514, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 806, in save
    self.save_base(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 857, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 1000, in _save_table
    results = self._do_insert(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 1041, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 1434, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1621, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 103, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "books_favorite_pkey"
DETAIL:  Key (id)=(144f51e8-a6de-4b5f-88c3-5706dd0bb3ff) already exists.

/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /admin/
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/models.py changed, reloading.
Watching for file changes with StatReloader
/code/books/models.py changed, reloading.
Watching for file changes with StatReloader
/code/books/models.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /favicon.ico/
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
/code/books/views.py changed, reloading.
Watching for file changes with StatReloader
